version: '3.7'
services:
  portainer:
        container_name: opendicom_portainer
        image: portainer/portainer-ce
        restart: unless-stopped
        environment:
            TZ: 'America/Montevideo'
        ports:
            - 8000:8000
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
volumes:
    portainer_data:
